toolbar:
  - styleselect | bold italic | undo redo
  - image | link
  - bullist | numlist
  - table | tabledelete | tableprops | tableinsertrowbefore tableinsertrowafter tabledeleterow
  - tableinsertcolbefore tableinsertcolafter tabledeletecol

plugins:
  - image
  - link
  - table
  - lists advlist